import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

type CommandModule = {
    className: string;
    importPath: string;
    isDefault: boolean;
};

const projectRoot = process.cwd();
const commandsDir = path.join(projectRoot, "src", "commands");
const outputFile = path.join(commandsDir, "generated.ts");

function collectCommandFiles(dir: string): string[] {
    return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
        const fullPath = path.join(dir, entry.name);

        if (entry.isDirectory()) {
            return collectCommandFiles(fullPath);
        }

        if (
            !entry.isFile() ||
            !entry.name.endsWith("Command.ts") ||
            entry.name === "Command.ts" ||
            entry.name === "generated.ts"
        ) {
            return [];
        }

        return [fullPath];
    });
}

function parseCommandModule(filePath: string): CommandModule {
    const source = readFileSync(filePath, "utf8");
    const match = source.match(/export\s+(default\s+)?class\s+([A-Za-z_$][\w$]*)/);

    if (!match) {
        throw new Error(`Could not find an exported command class in ${path.relative(projectRoot, filePath)}`);
    }

    const importPath = `./${path.relative(commandsDir, filePath).replace(/\\/g, "/").replace(/\.ts$/, "")}`;

    return {
        className: match[2],
        importPath,
        isDefault: Boolean(match[1]),
    };
}

const commandModules = collectCommandFiles(commandsDir).sort().map(parseCommandModule);

const fileContents = [
    "// This file is auto-generated by scripts/generate-command-registry.ts.",
    "// Do not edit manually.",
    "",
    'import type { Command } from "./Command";',
    ...commandModules.map((module) =>
        module.isDefault
            ? `import ${module.className} from "${module.importPath}";`
            : `import { ${module.className} } from "${module.importPath}";`,
    ),
    "",
    `export const commandConstructors: Array<new () => Command> = [${commandModules.map((module) => module.className).join(", ")}];`,
    "",
].join("\n");

writeFileSync(outputFile, fileContents);
process.stdout.write(
    `Generated ${path.relative(projectRoot, outputFile)} with ${commandModules.length} command modules.\n`,
);
