// This file is auto-generated by scripts/generate-command-registry.ts.
// Do not edit manually.

import type { Command } from "./Command";
import { ForceLinkCommand } from "./Link/ForceLinkCommand";
import { LinkCommand } from "./Link/LinkCommand";
import { TestConnectionCommand } from "./TestConnection/TestConnectionCommand";

export const commandConstructors: Array<new () => Command> = [ForceLinkCommand, LinkCommand, TestConnectionCommand];
